### PR TITLE
Updated types in `build.zig`

### PR DESCRIPTION
**Pull request by KenCox94**
Parameter mismatch that broke build:
   - updated first parameter `[]const u8` to `LazyPath`
   - updated final parameter to empty `HeaderInstallation.Directory.Options`

### CODE REVIEW

**Review by kassane — CHANGES_REQUESTED** [review]
Need some changes below (based on your fork):

```diff
diff --git a/build.zig b/build.zig
index 31dfc1d91f..82f30d448a 100644
--- a/build.zig
+++ b/build.zig
@@ -7,10 +7,10 @@ pub fn build(b: *std.Build) void {
     const crypto = libcrypto(b, target, optimize);
     const ssl = libssl(b, target, optimize);
 
-    crypto.installHeadersDirectory("include/crypto", "crypto");
-    crypto.installHeadersDirectory("include/internal", "internal");
-    ssl.installHeadersDirectory("include/openssl", "openssl");
-    ssl.installHeadersDirectory("include_gen", "");
+    crypto.installHeadersDirectory(b.path("include/crypto"), "crypto", .{});
+    crypto.installHeadersDirectory(b.path("include/internal"), "internal", .{});
+    ssl.installHeadersDirectory(b.path("include/openssl"), "openssl", .{});
+    ssl.installHeadersDirectory(b.path("include_gen"), "", .{});
     b.installArtifact(crypto);
     b.installArtifact(ssl);
 }
@@ -26,12 +26,12 @@ fn libcrypto(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.buil
         .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
         else => lib.root_module.strip = true,
     }
-    lib.addIncludePath(.{ .path = "include" });
-    lib.addIncludePath(.{ .path = "." });
-    lib.addIncludePath(.{ .path = "providers/common/include" });
-    lib.addIncludePath(.{ .path = "providers/fips" });
-    lib.addIncludePath(.{ .path = "providers/implementations/include" });
-    lib.addIncludePath(.{ .path = "include_gen" });
+    lib.addIncludePath(b.path("include"));
+    lib.addIncludePath(b.path("."));
+    lib.addIncludePath(b.path("providers/common/include"));
+    lib.addIncludePath(b.path("providers/fips"));
+    lib.addIncludePath(b.path("providers/implementations/include"));
+    lib.addIncludePath(b.path("include_gen"));
     // lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
     lib.defineCMacro("OPENSSL_NO_ENGINE", null);
     lib.defineCMacro("OPENSSL_NO_SRP", null);
@@ -887,8 +887,8 @@ fn libssl(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin
         .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
         else => lib.root_module.strip = true,
     }
-    lib.addIncludePath(.{ .path = "include" });
-    lib.addIncludePath(.{ .path = "include_gen" });
+    lib.addIncludePath(b.path("include"));
+    lib.addIncludePath(b.path("include_gen"));
     lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
     lib.defineCMacro("OPENSSL_NO_ENGINE", null);
     lib.defineCMacro("OPENSSL_NO_SRP", null);
@@ -997,13 +997,13 @@ fn libprovider(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.bu
         .target = target,
         .optimize = optimize,
     });
-    lib.addIncludePath(.{ .path = "include" });
-    lib.addIncludePath(.{ .path = "." });
-    lib.addIncludePath(.{ .path = "providers/common/include" });
-    lib.addIncludePath(.{ .path = "providers/fips" });
-    lib.addIncludePath(.{ .path = "providers/implementations/include" });
-    lib.addIncludePath(.{ .path = "include_gen" });
-    lib.addIncludePath(.{ .path = "crypto" });
+    lib.addIncludePath(b.path("include"));
+    lib.addIncludePath(b.path("."));
+    lib.addIncludePath(b.path("providers/common/include"));
+    lib.addIncludePath(b.path("providers/fips"));
+    lib.addIncludePath(b.path("providers/implementations/include"));
+    lib.addIncludePath(b.path("include_gen"));
+    lib.addIncludePath(b.path("crypto"));
     lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
     lib.defineCMacro("OPENSSL_NO_ENGINE", null);
     lib.defineCMacro("OPENSSL_NO_SRP", null);
@@ -1018,7 +1018,7 @@ fn libprovider(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.bu
         // CommonCrypto
         lib.linkFramework("CoreServices");
         lib.defineCMacro("OPENSSL_SYS_MACOSX", "1");
-        lib.addSystemIncludePath(.{ .path = "/usr/include" });
+        lib.addSystemIncludePath(b.path("/usr/include"));
     }
     if (lib.rootModuleTarget().isMinGW())
         lib.defineCMacro("NOCRYPT", "1");
```

**Comment by KenCox94** [comment]
> Need some changes below (based on your fork):
> 
> ```diff
> diff --git a/build.zig b/build.zig
> index 31dfc1d91f..82f30d448a 100644
> --- a/build.zig
> +++ b/build.zig
> @@ -7,10 +7,10 @@ pub fn build(b: *std.Build) void {
>      const crypto = libcrypto(b, target, optimize);
>      const ssl = libssl(b, target, optimize);
>  
> -    crypto.installHeadersDirectory("include/crypto", "crypto");
> -    crypto.installHeadersDirectory("include/internal", "internal");
> -    ssl.installHeadersDirectory("include/openssl", "openssl");
> -    ssl.installHeadersDirectory("include_gen", "");
> +    crypto.installHeadersDirectory(b.path("include/crypto"), "crypto", .{});
> +    crypto.installHeadersDirectory(b.path("include/internal"), "internal", .{});
> +    ssl.installHeadersDirectory(b.path("include/openssl"), "openssl", .{});
> +    ssl.installHeadersDirectory(b.path("include_gen"), "", .{});
>      b.installArtifact(crypto);
>      b.installArtifact(ssl);
>  }
> @@ -26,12 +26,12 @@ fn libcrypto(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.buil
>          .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
>          else => lib.root_module.strip = true,
>      }
> -    lib.addIncludePath(.{ .path = "include" });
> -    lib.addIncludePath(.{ .path = "." });
> -    lib.addIncludePath(.{ .path = "providers/common/include" });
> -    lib.addIncludePath(.{ .path = "providers/fips" });
> -    lib.addIncludePath(.{ .path = "providers/implementations/include" });
> -    lib.addIncludePath(.{ .path = "include_gen" });
> +    lib.addIncludePath(b.path("include"));
> +    lib.addIncludePath(b.path("."));
> +    lib.addIncludePath(b.path("providers/common/include"));
> +    lib.addIncludePath(b.path("providers/fips"));
> +    lib.addIncludePath(b.path("providers/implementations/include"));
> +    lib.addIncludePath(b.path("include_gen"));
>      // lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
>      lib.defineCMacro("OPENSSL_NO_ENGINE", null);
>      lib.defineCMacro("OPENSSL_NO_SRP", null);
> @@ -887,8 +887,8 @@ fn libssl(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin
>          .Debug, .ReleaseSafe => lib.bundle_compiler_rt = true,
>          else => lib.root_module.strip = true,
>      }
> -    lib.addIncludePath(.{ .path = "include" });
> -    lib.addIncludePath(.{ .path = "include_gen" });
> +    lib.addIncludePath(b.path("include"));
> +    lib.addIncludePath(b.path("include_gen"));
>      lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
>      lib.defineCMacro("OPENSSL_NO_ENGINE", null);
>      lib.defineCMacro("OPENSSL_NO_SRP", null);
> @@ -997,13 +997,13 @@ fn libprovider(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.bu
>          .target = target,
>          .optimize = optimize,
>      });
> -    lib.addIncludePath(.{ .path = "include" });
> -    lib.addIncludePath(.{ .path = "." });
> -    lib.addIncludePath(.{ .path = "providers/common/include" });
> -    lib.addIncludePath(.{ .path = "providers/fips" });
> -    lib.addIncludePath(.{ .path = "providers/implementations/include" });
> -    lib.addIncludePath(.{ .path = "include_gen" });
> -    lib.addIncludePath(.{ .path = "crypto" });
> +    lib.addIncludePath(b.path("include"));
> +    lib.addIncludePath(b.path("."));
> +    lib.addIncludePath(b.path("providers/common/include"));
> +    lib.addIncludePath(b.path("providers/fips"));
> +    lib.addIncludePath(b.path("providers/implementations/include"));
> +    lib.addIncludePath(b.path("include_gen"));
> +    lib.addIncludePath(b.path("crypto"));
>      lib.defineCMacro("OPENSSL_NO_DEPRECATED", null);
>      lib.defineCMacro("OPENSSL_NO_ENGINE", null);
>      lib.defineCMacro("OPENSSL_NO_SRP", null);
> @@ -1018,7 +1018,7 @@ fn libprovider(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.bu
>          // CommonCrypto
>          lib.linkFramework("CoreServices");
>          lib.defineCMacro("OPENSSL_SYS_MACOSX", "1");
> -        lib.addSystemIncludePath(.{ .path = "/usr/include" });
> +        lib.addSystemIncludePath(b.path("/usr/include"));
>      }
>      if (lib.rootModuleTarget().isMinGW())
>          lib.defineCMacro("NOCRYPT", "1");
> ```

since `addSystemIncludePath` is adding a system path I think your initial `.{ .path = "/usr/include" }` implementation is preferred. The `Builder.path` is including files relative to source project root. 

Let me know your thoughts

**Comment by kassane** [comment]
> since `addSystemIncludePath` is adding a system path I think your initial `.{ .path = "/usr/include" }` implementation is preferred. The `Builder.path` is including files relative to source project root.
> 
> Let me know your thoughts

Currently, `error: no field named 'path' in union 'Build.LazyPath'` (v0.13.0 and v0.14.0-dev), replaced to `.{.cwd_relative = "/"}` for absolute path or a path relative.

Ok! Try use in `addSystemIncludePath`, `.cwd_relative`.

**Review by kassane — APPROVED** [review]

**Comment by kassane** [comment]
Congratulations on your contribution. PR is always welcome.

**Pull request merged**
